language: node_js
node_js:
  - "6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq golang php5-cli ruby python pylint
 - npm install -g jshint coffeelint jsonlint js-yaml
 - git config --global user.email "travis@kvz.io"
 - git config --global user.name "Travis test user"
script: make test
